version: '3.9'
services:
  nginx:
    build:
      context: docker/development
      dockerfile: nginx/Dockerfile
    environment:
      SERVER_NAME: ${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    depends_on:
        - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/development/php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=${DOMAIN_NAME}
    volumes:
      - .:/app
      - ./var/xdebug:/tmp/xdebug

  php-cli:
    build:
      context: .
      dockerfile: docker/development/php-cli/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=${DOMAIN_NAME}
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
        - "3306:3306"
    volumes:
      - ./var/database:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql

